#!/usr/bin/env fish

# For logging
set _name ( path change-extension '' ( basename ( status filename )))

# Load colour and format variables
source "$ZAI_DIR/source/format.fish"

# Load helper functions
source "$ZAI_DIR/source/functions.fish"

txt_major "Preserving configuration for child scripts..."
echo '' >> "$(_log)"
echo "#!/usr/bin/env fish"									| tee -a "$(_log)"  > "/mnt/zai/env"
echo '#'													| tee -a "$(_log)" >> "/mnt/zai/env"
echo "# This file was generated by 'preserve_env.fish'"		| tee -a "$(_log)" >> "/mnt/zai/env"
echo "# Created on $(date --iso-8601)"						| tee -a "$(_log)" >> "/mnt/zai/env"
echo ''														| tee -a "$(_log)" >> "/mnt/zai/env"

for evar in (set --names)
	if string match -rq '^ZAI\_' $evar
		if string match -rvq '^ZAI\_DIR$' $evar
			echo "set -x $evar '$$evar'"					| tee -a "$(_log)" >> "/mnt/zai/env"
		end
	end
end
echo '' >> "$(_log)"

bat --paging never --language fish "/mnt/zai/env"

txt_major "Finished preserving configuration"
return
